### ISSUE TITLE
Turn info panel into an extension?

### ISSUE THREAD

**Issue by aldesantis** [seand7565/solidus-sample#10]
I think it would be very cool to turn the info panel into an extension, so that it can be added to real stores in order to train store admins after the launch and new store admins when they're onboarded.

We could probably do the same thing with the guided tour and just put them all under the same extension (solidus_backend_help/solidus_backend_guides?).

**Comment by seand7565** [comment]
I love this idea, and with the way it's set up now with the .yml file being loaded in at boot, it should be pretty easy to extend if stores wanted to add their custom controller/actions to the guide.

**Comment by seand7565** [comment]
Done! https://github.com/seand7565/solidus_user_guides
