### ISSUE TITLE
Reset data periodically

### ISSUE THREAD

**Issue by aldesantis** [seand7565/solidus-sample#11]
Whenever I've seen a public product demo, it was full of spam. I think we should create some recurring cronjob to reset the data periodically (e.g. every night). This should be easily doable with Heroku's API, or we may even just truncate all tables via Rails.

**Comment by seand7565** [comment]
I'm _hoping_ that this won't be a problem, since users are only allowed to do anything with ActiveRecord on the frontend - the extent of the damage should only be in carts... but people are creative, so you never know!

**Comment by seand7565** [comment]
With the most recent changes, users are now able to edit all objects, and create, edit and delete new objects. The only thing they can't do is delete sample data, but I think that's acceptable. It's all scoped to the user, so any changes I make aren't visible by you. 

We may want to explore doing this going forward if the DB starts to grow in size, but for now I think we're good! Feel free to reopen if you disagree!
